/**
 * Markdown Report Renderer — Phase 11
 * Generates clean, GitHub-flavored Markdown from structured report data.
 */

export const markdownRenderer = {
  /**
   * Generates Markdown string from structured report data.
   *
   * @param {object} report - Structured report from reportBuilder
   * @returns {string}
   */
  render(report) {
    const meta = report.metadata || {};
    const lines = [];

    // Header
    lines.push(`# ${report.title || 'Meeting Intelligence Report'}`);
    lines.push('');
    lines.push('---');
    lines.push(`- **Source:** ${meta.contentTitle || 'Recording'}`);
    lines.push(`- **Date:** ${meta.date ? new Date(meta.date).toLocaleDateString() : 'N/A'}`);
    lines.push(`- **Duration:** ${meta.formattedDuration || 'N/A'}`);
    lines.push(`- **Participants:** ${meta.participants?.join(', ') || 'Speaker 1'}`);
    lines.push(`- **Template:** ${meta.templateName || 'Meeting Report'} (${report.detailLevel || 'STANDARD'})`);
    lines.push('---');
    lines.push('');

    // Sections
    (report.sections || []).forEach((sec) => {
      lines.push(`## ${sec.title}`);
      lines.push('');

      switch (sec.type) {
        case 'paragraph': {
          lines.push(sec.content || '');
          lines.push('');
          break;
        }

        case 'topics': {
          (sec.items || []).forEach((t) => {
            const tc = t.timecode ? ` \`[${t.timecode}]\`` : '';
            lines.push(`- **${t.title}**${tc}`);
            if (t.summary) {
              lines.push(`  ${t.summary}`);
            }
          });
          lines.push('');
          break;
        }

        case 'decisions': {
          (sec.items || []).forEach((d) => {
            const tc = d.timecode ? ` _(${d.timecode})_` : '';
            const agreed = d.agreedBy?.length ? ` *(Agreed by: ${d.agreedBy.join(', ')})*` : '';
            lines.push(`- [x] **${d.title}**${tc}`);
            if (d.description && d.description !== d.title) {
              lines.push(`  ${d.description}${agreed}`);
            }
          });
          lines.push('');
          break;
        }

        case 'action_items': {
          lines.push('| Task | Owner | Deadline | Status |');
          lines.push('| :--- | :--- | :--- | :--- |');
          (sec.items || []).forEach((a) => {
            const task = (a.task || '-').replace(/\|/g, '-');
            const owner = (a.owner || '-').replace(/\|/g, '-');
            const dl = (a.deadline || '-').replace(/\|/g, '-');
            const status = (a.status || '-').replace(/\|/g, '-');
            lines.push(`| ${task} | ${owner} | ${dl} | ${status} |`);
          });
          lines.push('');
          break;
        }

        case 'key_points': {
          (sec.items || []).forEach((kp) => {
            const tc = kp.timecode ? ` \`(${kp.timecode})\`` : '';
            lines.push(`- ${kp.text}${tc}`);
          });
          lines.push('');
          break;
        }

        case 'highlights': {
          (sec.items || []).forEach((hl) => {
            const tc = hl.timecode ? ` \`[${hl.timecode}]\`` : '';
            lines.push(`- ★ **${hl.title}**${tc}`);
            if (hl.description) {
              lines.push(`  ${hl.description}`);
            }
          });
          lines.push('');
          break;
        }

        case 'participants': {
          (sec.items || []).forEach((spk) => {
            lines.push(`- **${spk.name}** — ${spk.speakingTimeFormatted} (${spk.turnCount} turns)`);
          });
          lines.push('');
          break;
        }

        case 'questions': {
          (sec.items || []).forEach((q) => {
            const tc = q.timecode ? ` \`(${q.timecode})\`` : '';
            lines.push(`- **Q:** ${q.question}${tc}`);
          });
          lines.push('');
          break;
        }

        case 'transcript': {
          (sec.items || []).forEach((item) => {
            lines.push(`**[${item.timecode}] ${item.speaker}:** ${item.text}`);
          });
          lines.push('');
          break;
        }

        default:
          break;
      }
    });

    lines.push('---');
    lines.push('_Generated by [WrapAI](https://wrapai.io) • From Content to Clarity_');

    return lines.join('\n');
  }
};
