/**
 * Plain Text Report Renderer — Phase 11
 */

export const txtRenderer = {
  /**
   * Generates formatted plain text from structured report data.
   *
   * @param {object} report
   * @returns {string}
   */
  render(report) {
    const meta = report.metadata || {};
    const lines = [];

    lines.push('============================================================');
    lines.push(`WRAPAI INTELLIGENCE REPORT: ${report.title || 'Meeting Report'}`.toUpperCase());
    lines.push('============================================================');
    lines.push(`Source:       ${meta.contentTitle || 'Recording'}`);
    lines.push(`Date:         ${meta.date ? new Date(meta.date).toLocaleDateString() : 'N/A'}`);
    lines.push(`Duration:     ${meta.formattedDuration || 'N/A'}`);
    lines.push(`Participants: ${meta.participants?.join(', ') || 'Speaker 1'}`);
    lines.push('------------------------------------------------------------\n');

    (report.sections || []).forEach((sec) => {
      lines.push(`[${sec.title.toUpperCase()}]`);
      lines.push('------------------------------------------------------------');

      switch (sec.type) {
        case 'paragraph':
          lines.push(sec.content || '');
          break;

        case 'topics':
          (sec.items || []).forEach((t) => {
            lines.push(`* ${t.title} [${t.timecode || ''}]`);
            if (t.summary) lines.push(`  ${t.summary}`);
          });
          break;

        case 'decisions':
          (sec.items || []).forEach((d) => {
            lines.push(`[X] ${d.title} (${d.timecode || ''})`);
            if (d.description && d.description !== d.title) lines.push(`    ${d.description}`);
          });
          break;

        case 'action_items':
          (sec.items || []).forEach((a) => {
            lines.push(`[ ] ${a.task} | Owner: ${a.owner} | Due: ${a.deadline} | Status: ${a.status}`);
          });
          break;

        case 'key_points':
          (sec.items || []).forEach((kp) => {
            lines.push(`- ${kp.text} (${kp.timecode || ''})`);
          });
          break;

        case 'highlights':
          (sec.items || []).forEach((hl) => {
            lines.push(`* ${hl.title} [${hl.timecode || ''}]`);
            if (hl.description) lines.push(`  ${hl.description}`);
          });
          break;

        case 'participants':
          (sec.items || []).forEach((spk) => {
            lines.push(`- ${spk.name}: ${spk.speakingTimeFormatted} (${spk.turnCount} turns)`);
          });
          break;

        case 'questions':
          (sec.items || []).forEach((q) => {
            lines.push(`Q: ${q.question} (${q.timecode || ''})`);
          });
          break;

        default:
          break;
      }
      lines.push('');
    });

    lines.push('============================================================');
    lines.push('Generated by WrapAI • From Content to Clarity');
    lines.push('============================================================');

    return lines.join('\n');
  }
};
