import apiClient, { createApiResponse, mockDelay } from './api.js';
import { mockIntelligence } from '../mocks/mockIntelligence.js';

let localIntelligence = { ...mockIntelligence };

export const intelligenceService = {
  /**
   * Fetch structured intelligence analysis from backend API
   */
  async getIntelligence(contentId) {
    try {
      const res = await apiClient.get(`/content/${contentId}/analysis`);
      if (res && (res.data || res.summary)) {
        return res;
      }
      return createApiResponse(res);
    } catch (err) {
      console.warn(`Live analysis fetch failed for ${contentId} (${err.message}). Falling back to local/mock.`);
      await mockDelay(200);
      const data = localIntelligence[contentId] || localIntelligence['cnt_01'] || {
        summary: {
          short: 'Automated executive summary generated by WrapAI Content Intelligence Engine.',
          executive: 'Discussion on architecture milestones, database scaling, and execution deliverables.',
          keyTakeaway: 'The team approved the core technical roadmap and assigned next sprint actions.'
        },
        topics: [],
        keyPoints: [],
        decisions: [],
        actionItems: [],
        highlights: []
      };
      return createApiResponse(data);
    }
  },

  /**
   * Trigger LLM re-analysis in BullMQ background queue
   */
  async regenerateAnalysis(contentId) {
    try {
      const res = await apiClient.post(`/content/${contentId}/analyze`);
      return res;
    } catch (err) {
      console.warn(`Re-analysis trigger failed for ${contentId}: ${err.message}`);
      await mockDelay(300);
      return createApiResponse({ jobId: `job_mock_${Date.now()}`, status: 'QUEUED' }, 'Re-analysis enqueued');
    }
  },

  /**
   * Update action item status or details
   */
  async updateActionItemStatus(contentId, actionId, newStatus) {
    try {
      const res = await apiClient.patch(`/content/${contentId}/action-items/${actionId}`, {
        status: newStatus.toUpperCase().replace(/\s+/g, '_')
      });
      return res;
    } catch (err) {
      console.warn(`Live action item update failed: ${err.message}. Falling back to local state.`);
      await mockDelay(150);
      const key = localIntelligence[contentId] ? contentId : 'cnt_01';
      const intel = localIntelligence[key];
      if (intel && intel.actionItems) {
        intel.actionItems = intel.actionItems.map((a) => (a.id === actionId ? { ...a, status: newStatus } : a));
      }
      return createApiResponse(intel?.actionItems || [], 'Action item status updated');
    }
  },

  /**
   * Update decision details
   */
  async updateDecision(contentId, decisionId, updates) {
    try {
      const res = await apiClient.patch(`/content/${contentId}/decisions/${decisionId}`, updates);
      return res;
    } catch (err) {
      console.warn(`Live decision update failed: ${err.message}`);
      return createApiResponse(updates, 'Decision updated');
    }
  }
};
