import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { intelligenceService } from '../../../../services/intelligenceService.js';
import { Card } from '../../../../components/ui/Card.jsx';
import { Badge } from '../../../../components/ui/Badge.jsx';
import { LoadingState } from '../../../../components/common/LoadingState.jsx';
import { FileText, Sparkles, RefreshCw, CheckCircle2, Cpu } from 'lucide-react';

export function SummaryTab() {
  const { id } = useParams();
  const [intel, setIntel] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isReanalyzing, setIsReanalyzing] = useState(false);
  const [reanalyzeMsg, setReanalyzeMsg] = useState(null);

  const loadData = async () => {
    try {
      const res = await intelligenceService.getIntelligence(id);
      setIntel(res.data || res);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [id]);

  const handleReanalyze = async () => {
    setIsReanalyzing(true);
    setReanalyzeMsg(null);
    try {
      const res = await intelligenceService.regenerateAnalysis(id);
      setReanalyzeMsg('Re-analysis job enqueued successfully! Results will update in background.');
    } catch (err) {
      setReanalyzeMsg('Failed to trigger re-analysis.');
    } finally {
      setIsReanalyzing(false);
    }
  };

  if (isLoading) return <LoadingState message="Extracting summary insights..." />;

  const summary = intel?.summary;
  const takeaway = summary?.keyTakeaway || summary?.takeaway || 'Key takeaways extracted from transcript.';
  const executive = summary?.executive || summary?.executiveSummary || summary?.short || 'Executive summary generated by WrapAI.';
  const detailed = summary?.detailed || summary?.detailedSummary || summary?.overview || '';
  const provider = intel?.llmProvider || 'heuristic';
  const model = intel?.llmModel || 'gemini-2.5-flash';

  return (
    <div className="space-y-8 max-w-5xl">
      {/* Re-analysis Banner & Provenance */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 bg-brand-sage/20 border border-brand-sage/40">
        <div className="flex items-center space-x-2">
          <Badge variant="cyan" className="font-mono text-[10px] uppercase">
            <Cpu className="w-3 h-3 mr-1 inline" /> AI Generated ({model})
          </Badge>
          <span className="text-xs text-brand-taupe">Factual claims traceable to transcript</span>
        </div>

        <button
          onClick={handleReanalyze}
          disabled={isReanalyzing}
          className="inline-flex items-center text-xs font-bold uppercase tracking-wider text-brand-navy hover:text-brand-charcoal bg-brand-white border border-brand-charcoal/20 px-3 py-1.5 shadow-sm hover:bg-brand-sage/30 transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-3.5 h-3.5 mr-1.5 ${isReanalyzing ? 'animate-spin' : ''}`} />
          {isReanalyzing ? 'Enqueuing...' : 'Re-analyze with AI'}
        </button>
      </div>

      {reanalyzeMsg && (
        <div className="p-3 bg-emerald-50 border border-emerald-300 text-emerald-800 text-xs font-mono">
          {reanalyzeMsg}
        </div>
      )}

      {/* 1. Main Takeaway Callout */}
      <Card className="bg-brand-navy text-brand-white p-6 sm:p-8 border border-brand-charcoal">
        <div className="flex items-center space-x-2 text-brand-cyan mb-2">
          <Sparkles className="w-4 h-4" />
          <span className="text-[11px] font-mono uppercase font-bold tracking-widest">CORE TAKEAWAY</span>
        </div>
        <p className="text-base sm:text-lg font-medium text-brand-light leading-relaxed">
          {takeaway}
        </p>
      </Card>

      {/* 2. Executive Summary */}
      <Card className="p-8">
        <h2 className="font-display text-2xl uppercase tracking-wide text-brand-navy mb-4 flex items-center">
          <FileText className="w-5 h-5 mr-2 text-brand-navy" /> Executive Summary
        </h2>
        <p className="text-sm text-brand-charcoal leading-relaxed whitespace-pre-line">
          {executive}
        </p>
      </Card>

      {/* 3. Detailed / Context Breakdown */}
      {detailed && (
        <Card className="p-8">
          <h2 className="font-display text-2xl uppercase tracking-wide text-brand-navy mb-4">
            Context & Discussion Overview
          </h2>
          <p className="text-sm text-brand-charcoal leading-relaxed whitespace-pre-line">
            {detailed}
          </p>
        </Card>
      )}
    </div>
  );
}
