export const CONTENT_TYPES = {
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  TEXT: 'TEXT',
  URL: 'URL'
};

export const PROCESSING_STATUS = {
  UPLOADED: 'UPLOADED',
  QUEUED: 'QUEUED',
  VALIDATING: 'VALIDATING',
  PREPARING: 'PREPARING',
  PROCESSING: 'PROCESSING',
  AUDIO_EXTRACTION: 'AUDIO_EXTRACTION',
  TRANSCRIBING: 'TRANSCRIBING',
  DIARIZING: 'DIARIZING',
  ALIGNING_SPEAKERS: 'ALIGNING_SPEAKERS',
  SAVING_TRANSCRIPT: 'SAVING_TRANSCRIPT',
  ANALYZING: 'ANALYZING',
  GENERATING_EMBEDDINGS: 'GENERATING_EMBEDDINGS',
  GENERATING_REPORT: 'GENERATING_REPORT',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const REPORT_TYPES = {
  MEETING_MINUTES: 'MEETING_MINUTES',
  LECTURE_NOTES: 'LECTURE_NOTES',
  INTERVIEW_SUMMARY: 'INTERVIEW_SUMMARY',
  EXECUTIVE_BRIEF: 'EXECUTIVE_BRIEF'
};
