export const CONTENT_TYPES = {
  AUDIO: 'AUDIO',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
  TEXT: 'TEXT',
  URL: 'URL'
};

export const PROCESSING_STATUS = {
  UPLOADED: 'UPLOADED',
  QUEUED: 'QUEUED',
  VALIDATING: 'VALIDATING',
  PREPARING: 'PREPARING',
  PROCESSING: 'PROCESSING',
  AUDIO_EXTRACTION: 'AUDIO_EXTRACTION',
  TRANSCRIBING: 'TRANSCRIBING',
  DIARIZING: 'DIARIZING',
  ALIGNING_SPEAKERS: 'ALIGNING_SPEAKERS',
  SAVING_TRANSCRIPT: 'SAVING_TRANSCRIPT',
  ANALYZING: 'ANALYZING',
  ANALYZING_CONTENT: 'ANALYZING_CONTENT',
  SAVING_ANALYSIS: 'SAVING_ANALYSIS',
  // Phase 10: Vector indexing stages
  CHUNKING: 'CHUNKING',
  GENERATING_EMBEDDINGS: 'GENERATING_EMBEDDINGS',
  INDEXING: 'INDEXING',
  // Report
  GENERATING_REPORT: 'GENERATING_REPORT',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

export const REPORT_TYPES = {
  MEETING_REPORT: 'MEETING_REPORT',
  MEETING_MINUTES: 'MEETING_MINUTES',
  EXECUTIVE_SUMMARY: 'EXECUTIVE_SUMMARY',
  EXECUTIVE_BRIEF: 'EXECUTIVE_BRIEF',
  LECTURE_NOTES: 'LECTURE_NOTES',
  INTERVIEW_REPORT: 'INTERVIEW_REPORT',
  INTERVIEW_SUMMARY: 'INTERVIEW_SUMMARY',
  GENERAL_REPORT: 'GENERAL_REPORT'
};

export const REPORT_FORMATS = {
  PDF: 'PDF',
  DOCX: 'DOCX',
  MARKDOWN: 'MARKDOWN',
  TXT: 'TXT'
};

export const REPORT_DETAIL_LEVELS = {
  BRIEF: 'BRIEF',
  STANDARD: 'STANDARD',
  DETAILED: 'DETAILED'
};

export const REPORT_STATUS = {
  QUEUED: 'QUEUED',
  GENERATING: 'GENERATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};
